# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
        ('trail_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trails',
            name='name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trails',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='login_reg_app.Users'),
            preserve_default=False,
        ),
    ]
