# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
        ('trail_app', '0002_auto_20181119_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='trails',
            name='wish_list_users',
            field=models.ManyToManyField(related_name='wish_list_trails', to='login_reg_app.Users'),
        ),
    ]
