# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=255)),
                ('avg_bpm', models.IntegerField(null=True)),
                ('max_bpm', models.IntegerField(null=True)),
                ('calories', models.IntegerField()),
                ('pace', models.CharField(max_length=255)),
                ('steps', models.IntegerField(null=True)),
                ('elevation', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='reports.Reports')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='login_reg_app.Users')),
            ],
        ),
    ]
